name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./time_manager
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/timemanagerbackend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./time_manager_front
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/timemanagerfrontend:latest

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PEM }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY_PEM }}
          script: |
            cd TimeManager
            git pull origin main
            docker-compose down
            docker-compose pull
            docker-compose up -d